spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/syonet
    username: syonet
    password: syonet
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC

server:
  port: 8080